name: code_extension
description: Ozon barcode generator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  barcode_widget: ^2.0.4
  pdf: ^3.10.1
  barcode_image: ^2.0.3
  file_selector: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true

  fonts:
    - family: Sans
      fonts:
        - asset: fonts/PTSans-Regular.ttf
          weight: 400
        - asset: fonts/PTSans-Bold.ttf
          weight: 700
        

